package com.squeed.chromequiz.channel;

public enum EventDef {
	EVENT_QUESTION, EVENT_ANSWER, EVENT_GAME_STARTED, EVENT_GAME_FINISHED, EVENT_GAME_MASTER_TRUE, EVENT_GAME_MASTER_FALSE, EVENT_START_GAME, EVENT_NAME_REQUEST_RESPONSE, EVENT_QUESTION_TIMEOUT;
}
